name: 'tf deploy to azure'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform initializing'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    
    - name: Checkout
      uses: actions/setup-terraform@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init
      run: terraform init
    