name: 'tf deploy to azure'

on:
  push:
    branches:
    - main
  pull_request:

env:
  ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID_NONPROD}}
  ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET_NONPROD}}
  ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID_NONPROD}}
  ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}


jobs:
  terraform:
    name: 'Terraform initializing'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init
      run: terraform init
    
    - name: Terraform plan
      run: terraform plan